<h3>Sponsorship Inquiry</h3>

<form action="mailto:aminfamily@email.com" method="post" enctype="text/plain">
    <input type="text" name="Name" placeholder="Your Name" required><br><br>
    <input type="email" name="Email" placeholder="Your Email" required><br><br>
    <textarea name="Message" placeholder="Why do you want to sponsor us?" required></textarea><br><br>
    <button type="submit">Send Inquiry</button>
</form>
